version: '3'

tasks:
  dev:fe:
    desc: Start local development server with hot reload
    cmds:
      - npm run dev
  
  dev:be:
    desc: Run production build locally with Cloudflare Functions
    cmds:
      - task: build
      - npm run dev:be

  dev:full:
    desc: Start Astro dev server (4321) + Wrangler Worker (8788) with hot reload
    cmds:
      - task: build
      - npm run dev:full

  create:
    desc: Create a new article folder in src/content/articles
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Usage: task create -- <article-name>"
    cmds:
      - mkdir -p src/content/articles/{{.CLI_ARGS}}
      - |
        cat > src/content/articles/{{.CLI_ARGS}}/index.md << 'EOF'
        ---
        title: "{{.CLI_ARGS | title}}"
        date: $(date +%Y-%m-%d)
        description: "A brief description of the article"
        tags:
          - tag1
          - tag2
        ---

        # Introduction

        Write your article content here...

        ## Code Example

        ```typescript
        // Your code here
        ```

        ## Conclusion

        Wrap up your thoughts...
        EOF
      - echo "Created article at src/content/articles/{{.CLI_ARGS}}/index.md"

  scripts:setup:
    desc: Setup Python virtual environment and install dependencies
    cmds:
      - python3 -m venv scripts/.venv
      - scripts/.venv/bin/pip install -r scripts/requirements.txt
    sources:
      - scripts/requirements.txt
    generates:
      - scripts/.venv/bin/activate

  index:build:
    desc: Generate search index from articles
    deps:
      - scripts:setup
    cmds:
      - scripts/.venv/bin/python scripts/build_search_index.py

  build:
    desc: Build the site for production
    cmds:
      - task: index:build
      - npm run build

  preview:
    desc: Preview the production build locally
    cmds:
      - npm run preview

  r2:create:
    desc: Create R2 bucket for search index
    cmds:
      - npx wrangler r2 bucket create onebytepls-search-index

  r2:upload:
    desc: Upload search index to R2 bucket
    cmds:
      - npx wrangler r2 object put onebytepls-search-index/search-index.json --file=public/search-index.json --remote

  deploy:
    desc: Build, upload search index to R2, and deploy Worker to Cloudflare
    cmds:
      - task: build
      - task: r2:upload
      - npx wrangler deploy